### ISSUE TITLE
Incremental rebuild not working

### ISSUE THREAD

**Issue by simonihmig** [simonihmig/ember-responsive-image#25]
When I add a new image, this does not trigger resizing of the new image, and a new rebuild of the meta data. Instead this happens:

![image](https://user-images.githubusercontent.com/1325249/31236615-e5909120-a9f4-11e7-8354-3547ab8e65a5.png)

Ideally, it would not rescale all images, but only the changed ones. But even rescaling all images would be better than having to restart the `ember server`.

**Comment by devotox** [comment]
Will this be looked into?

**Comment by simonihmig** [comment]
This seems to work now, with the major overhaul for the upcoming v2. At least new images are picked up. Deleting files caused build errors for me, but they stemmed from other addons (`broccoli-asset-rev` and `ember-auto-import`). Closing this therefore, sorry for the long delay here!
