### ISSUE TITLE
Disable incremental rebuild?

### ISSUE THREAD

**Issue by nova-alex** [simonihmig/ember-responsive-image#445]
Genius plugin and exemplary implementation. I'm delighted at the usability and power it adds to my project.

I'm under a bit of a performance crunch on my ember-cli implementation and with over 1000 images in my assets folder it takes a very long time for livereload to rescan the folder for changes. > 6000ms.

As I'm not adding images to my project on the fly, I wonder if there is a way I could have ember-responsive-image do its thing just once on startup and not monitor the assets folder for changes after that?

Very grateful for your assistance in this matter!

**Comment by simonihmig** [comment]
I am surprised it takes so long, as it should be cached. How do you know about this number of 6000ms, does ember-cli emit this on the terminal? Can you post a screenshot?

**Comment by nova-alex** [comment]
Hi! I think it was a problem with my environment. Unfortunately I've only got access to `git-bash` on my work PC and I think performance is very slow in some cases when running as a user rather than administrator. I'm glad to report that the plugin refreshes very quickly.

**Comment by simonihmig** [comment]
ok, glad to hear that, and thanks for reporting back!
