### ISSUE TITLE
ember-responsive-image@5.0.0-beta.0 / Cannot find module 

### ISSUE THREAD

**Issue by BenjaminBeck** [simonihmig/ember-responsive-image#549]
After installing the beta i get this error when running ember serve:

Cannot find module '/ < ember-project-dir > /config/addons'
Require stack:
/ < ember-project-dir > /node_modules/.pnpm/ember-addon-config@0.1.0_@glint+template@1.2.1/node_modules/ember-addon-config/index.js

Its a pretty new ember app with embroider.

Thanks for your work on this addon.

Greetings
Benjamin

**Comment by simonihmig** [comment]
yeah, that's a bug. You need to create that file as described in https://github.com/simonihmig/ember-responsive-image?tab=readme-ov-file#configuration to get around this, even if the config is empty.

The underlying implementation will change before a stable 5.0.0, and of course shouldn't fail if non-existent.
