### ISSUE TITLE
Addon doesn't work as a nested dependency

### ISSUE THREAD

**Issue by mansona** [simonihmig/ember-responsive-image#73]
Hey folks 👋  First of all I want to say thanks for a great addon! It's super useful and I'm trying to make it a key addon in a lot of the empress projects 🎉 

I'm having a few issues right now where I want to make this addon work as a dependency of a dependency. There are a few issues that stem from the fact that certain hooks are not called in a nested fashion (like `contentFor()` https://github.com/ember-cli/ember-cli/issues/8077) but there are other issues that seem to stem from the fact that we seem to have quite a few local variables in the addon that are not part of the general addon spec 🤔 

You can see my attempts to defer some of the implementation of `contentFor()` and `postProcessTree()` to `ember-responsive-image` here https://github.com/empress/empress-blog-casper-template/pull/37 but as you can see from the Netlify demo apps and build history, I'm not getting very far 🙈 

If you have any advice on how to proceed that would be super useful 👍

**Comment by simonihmig** [comment]
Heya, sorry for the late reply! This slipped through... 😔 

I am currently working on a major overhaul of the addon (in the `dev-v2` branch). One related change is that `postProcessTree()` won't be used anymore (as that makes it incompatible with Embroider), instead the resized images are now exposed to the app through `treeForPublic`,  which *should* work even as a nested dependency AFAIK.

However the issue with `contentFor` remains.

I am just not sure if using this addon as a nested dependency is really "correct" here. It would be more so if it would do its work only on the images of the primary addon, and not expose its functionality to the app directly. But the opposite is the case, the addon explicitly looks for images of the host app, and fundamentally changes how these images are processed for the app's `dist` output, so I think it should also be "owned" by the app!? 🤔

Do you see any downside of adding the addon to the host app by the blueprint?

**Comment by elwayman02** [comment]
@mansona can this ticket be closed now?

**Comment by simonihmig** [comment]
With the upcoming release of this addon in v2 format, I think this problem becomes irrelevant, so closing this.
